# -*- coding: utf-8 -*-
"""proyectofinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jXx6o3KusAmsLAgMeRxWiKpUiZVPDOZ5
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

mode = "right_to_left"
physics = "rk4"
n_rays = 18
view_radius = 6.0
r_h = 1.0
dt = 0.05
frames = 800
trail_max_len = 60
bend_strength = 0.5

# RK4

def acceleration(x, y, vx, vy, k=bend_strength):
    """Aceleración radial tipo -k * r_hat / r^2 (visual, no exacta relativista).
       k controla la intensidad de la desviación."""
    r = np.sqrt(x*x + y*y)
    if r == 0:
        return 0.0, 0.0
    ax = -k * x / (r**3)
    ay = -k * y / (r**3)
    return ax, ay

def rk4_step(x, y, vx, vy, dt):
    """Un paso RK4 para sistema x' = vx, vx' = ax(x,y,vx,vy)."""
    ax1, ay1 = acceleration(x, y, vx, vy)
    k1x, k1y = vx, vy
    k1vx, k1vy = ax1, ay1

    ax2, ay2 = acceleration(x + 0.5*dt*k1x, y + 0.5*dt*k1y,
                           vx + 0.5*dt*k1vx, vy + 0.5*dt*k1vy)
    k2x, k2y = vx + 0.5*dt*k1vx, vy + 0.5*dt*k1vy
    k2vx, k2vy = ax2, ay2

    ax3, ay3 = acceleration(x + 0.5*dt*k2x, y + 0.5*dt*k2y,
                           vx + 0.5*dt*k2vx, vy + 0.5*dt*k2vy)
    k3x, k3y = vx + 0.5*dt*k2vx, vy + 0.5*dt*k2vy
    k3vx, k3vy = ax3, ay3

    ax4, ay4 = acceleration(x + dt*k3x, y + dt*k3y,
                           vx + dt*k3vx, vy + dt*k3vy)
    k4x, k4y = vx + dt*k3vx, vy + dt*k3vy
    k4vx, k4vy = ax4, ay4

    x_new = x + dt*(k1x + 2*k2x + 2*k3x + k4x)/6
    y_new = y + dt*(k1y + 2*k2y + 2*k3y + k4y)/6
    vx_new = vx + dt*(k1vx + 2*k2vx + 2*k3vx + k4vx)/6
    vy_new = vy + dt*(k1vy + 2*k2vy + 2*k3vy + k4vy)/6

    return x_new, y_new, vx_new, vy_new


def init_right_to_left(n, x_start= view_radius, y_min=-0.9, y_max=0.9):
    xs = np.full(n, x_start, dtype=float)
    ys = np.linspace(y_min, y_max, n, dtype=float)
    vxs = -0.6 * np.ones(n)   # velocidad inicial hacia la izquierda
    vys = np.zeros(n)
    return xs, ys, vxs, vys

def init_circle_in(n, radius=view_radius, center=(0.0,0.0)):
    thetas = np.linspace(0, 2*np.pi, n, endpoint=False)
    cx, cy = center
    xs = cx + radius * np.cos(thetas)
    ys = cy + radius * np.sin(thetas)
    vxs = -np.cos(thetas) * 0.6
    vys = -np.sin(thetas) * 0.6
    return xs, ys, vxs, vys

def init_point_emission(n, point=(-view_radius, 0.0), spread=0.6):
    px, py = point
    angles = np.linspace(-spread, spread, n)
    xs = np.full(n, px, dtype=float)
    ys = np.full(n, py, dtype=float)
    vxs = np.cos(angles) * 0.6
    vys = np.sin(angles) * 0.6
    return xs, ys, vxs, vys

if mode == "right_to_left":
    x_init, y_init, vx_init, vy_init = init_right_to_left(n_rays)
elif mode == "circle_in":
    x_init, y_init, vx_init, vy_init = init_circle_in(n_rays)
elif mode == "point_emission":
    x_init, y_init, vx_init, vy_init = init_point_emission(n_rays)
else:
    raise ValueError("mode desconocido")

x = x_init.copy()
y = y_init.copy()
vx = vx_init.copy()
vy = vy_init.copy()
alive = np.ones(n_rays, dtype=bool)

# estelas
paths_x = [[] for _ in range(n_rays)]
paths_y = [[] for _ in range(n_rays)]

fig, ax = plt.subplots(figsize=(6,6))
ax.set_xlim(-view_radius, view_radius)
ax.set_ylim(-view_radius, view_radius)
ax.set_aspect('equal', adjustable='box')
ax.set_facecolor('black')
ax.tick_params(colors='white')
ax.set_title("Rayos alrededor de agujero negro (RK4)")

horizon_circle = plt.Circle((0.0, 0.0), r_h, color='black', zorder=6)
ax.add_artist(horizon_circle)

for k in range(1, 10):
    ax.add_artist(plt.Circle((0,0), r_h + 0.02*k, color='orange', alpha=0.03, zorder=5-k))


traj_lines = [ax.plot([], [], lw=1.0, color='yellow', alpha=0.75)[0] for _ in range(n_rays)]
dots = [ax.plot([], [], 'o', color='white', markersize=4, zorder=7)[0] for _ in range(n_rays)]

def update(frame):
    for i in range(n_rays):

        if not alive[i]:
            traj_lines[i].set_data([], []); dots[i].set_data([], [])
            continue

        if physics == "rk4":
            x_new, y_new, vx_new, vy_new = rk4_step(x[i], y[i], vx[i], vy[i], dt)
        else:
            x_new = x[i] + vx[i] * dt
            y_new = y[i] + vy[i] * dt
            vx_new = vx[i]
            vy_new = vy[i]

        x[i], y[i], vx[i], vy[i] = x_new, y_new, vx_new, vy_new

        r = np.sqrt(x[i]**2 + y[i]**2)

        if r <= r_h:
            alive[i] = False
            paths_x[i] = []
            paths_y[i] = []
            traj_lines[i].set_data([], [])
            dots[i].set_data([], [])
            continue

        paths_x[i].append(float(x[i]))
        paths_y[i].append(float(y[i]))
        if len(paths_x[i]) > trail_max_len:
            paths_x[i].pop(0); paths_y[i].pop(0)

        traj_lines[i].set_data(list(paths_x[i]), list(paths_y[i]))
        dots[i].set_data([float(x[i])], [float(y[i])])

    return traj_lines + dots

anim = FuncAnimation(fig, update, frames=frames, interval=30, blit=False)

HTML(anim.to_jshtml())

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

mode = "corner_top_left"
physics = "rk4"
n_rays = 160
view_radius = 6.0
r_h = 1.0
dt = 0.05
frames = 2000
trail_max_len = 80
bend_strength = 0.6

def acceleration(x, y, vx, vy, k=bend_strength):
    """Aceleración visual que atrae hacia el origen (-k * r_hat / r^2)."""
    r = np.hypot(x, y)
    if r == 0:
        return 0.0, 0.0
    ax = -k * x / (r**3)
    ay = -k * y / (r**3)
    return ax, ay

def rk4_step(x, y, vx, vy, dt):
    ax1, ay1 = acceleration(x, y, vx, vy)
    k1x, k1y = vx, vy
    k1vx, k1vy = ax1, ay1

    ax2, ay2 = acceleration(x + 0.5*dt*k1x, y + 0.5*dt*k1y,
                           vx + 0.5*dt*k1vx, vy + 0.5*dt*k1vy)
    k2x, k2y = vx + 0.5*dt*k1vx, vy + 0.5*dt*k1vy
    k2vx, k2vy = ax2, ay2

    ax3, ay3 = acceleration(x + 0.5*dt*k2x, y + 0.5*dt*k2y,
                           vx + 0.5*dt*k2vx, vy + 0.5*dt*k2vy)
    k3x, k3y = vx + 0.5*dt*k2vx, vy + 0.5*dt*k2vy
    k3vx, k3vy = ax3, ay3

    ax4, ay4 = acceleration(x + dt*k3x, y + dt*k3y,
                           vx + dt*k3vx, vy + dt*k3vy)
    k4x, k4y = vx + dt*k3vx, vy + dt*k3vy
    k4vx, k4vy = ax4, ay4

    x_new = x + dt*(k1x + 2*k2x + 2*k3x + k4x)/6
    y_new = y + dt*(k1y + 2*k2y + 2*k3y + k4y)/6
    vx_new = vx + dt*(k1vx + 2*k2vx + 2*k3vx + k4vx)/6
    vy_new = vy + dt*(k1vy + 2*k2vy + 2*k3vy + k4vy)/6

    return x_new, y_new, vx_new, vy_new

def init_from_corner_top_left(n, corner_x=-view_radius, corner_y=+view_radius, spread_angle=0.7, speed=1.2):
    """
    Genera n rayos desde la esquina superior izquierda (corner_x, corner_y).
    Los angulos apuntan hacia el centro con un pequeño spread para variedad.
    """
    px, py = corner_x, corner_y
    vec = np.array([ -px, -py ])
    base_angle = np.arctan2(vec[1], vec[0])
    angles = base_angle + np.linspace(-spread_angle, spread_angle, n)
    xs = np.full(n, px, dtype=float)
    ys = np.full(n, py, dtype=float)
    vxs = np.cos(angles) * speed
    vys = np.sin(angles) * speed
    norms = np.hypot(vxs, vys)
    vxs = vxs / norms * (0.8)
    vys = vys / norms * (0.8)
    return xs, ys, vxs, vys

x_init, y_init, vx_init, vy_init = init_from_corner_top_left(n_rays)

x = x_init.copy()
y = y_init.copy()
vx = vx_init.copy()
vy = vy_init.copy()
alive = np.ones(n_rays, dtype=bool)

paths_x = [[] for _ in range(n_rays)]
paths_y = [[] for _ in range(n_rays)]

fig, ax = plt.subplots(figsize=(6,6))
ax.set_xlim(-view_radius, view_radius)
ax.set_ylim(-view_radius, view_radius)
ax.set_aspect('equal', adjustable='box')
ax.set_facecolor('black')
ax.tick_params(colors='white')
ax.set_title("Haces desde esquina superior izquierda → Agujero negro")

horizon_circle = plt.Circle((0.0, 0.0), r_h, color='black', zorder=6)
ax.add_artist(horizon_circle)
for k in range(1, 10):
    ax.add_artist(plt.Circle((0,0), r_h + 0.02*k, color='orange', alpha=0.03, zorder=5-k))

traj_lines = [ax.plot([], [], lw=1.0, color='yellow', alpha=0.8)[0] for _ in range(n_rays)]
dots = [ax.plot([], [], 'o', color='white', markersize=3, zorder=8)[0] for _ in range(n_rays)]

def update(frame):
    for i in range(n_rays):

        if not alive[i]:
            traj_lines[i].set_data([], []); dots[i].set_data([], [])
            continue

        if physics == "rk4":
            x_new, y_new, vx_new, vy_new = rk4_step(x[i], y[i], vx[i], vy[i], dt)
        else:
            x_new = x[i] + vx[i] * dt
            y_new = y[i] + vy[i] * dt
            vx_new = vx[i]; vy_new = vy[i]

        x[i], y[i], vx[i], vy[i] = x_new, y_new, vx_new, vy_new

        r = np.hypot(x[i], y[i])

        if r <= r_h:
            alive[i] = False
            paths_x[i] = []
            paths_y[i] = []
            traj_lines[i].set_data(paths_x[i], paths_y[i])
            dots[i].set_data([], [])
            continue

        paths_x[i].append(float(x[i]))
        paths_y[i].append(float(y[i]))
        if len(paths_x[i]) > trail_max_len:
            paths_x[i].pop(0); paths_y[i].pop(0)

        traj_lines[i].set_data(list(paths_x[i]), list(paths_y[i]))
        dots[i].set_data([float(x[i])], [float(y[i])])

    return traj_lines + dots

anim = FuncAnimation(fig, update, frames=frames, interval=30, blit=False)

HTML(anim.to_jshtml())

import numpy as np
import matplotlib.pyplot as plt
from tqdm.notebook import trange
from matplotlib.colors import Normalize
import time

mode = "corner_top_left"
n_rays = 1200
steps_max = 800
dt = 0.04
view_radius = 6.0
r_h = 1.0
bend_strength = 0.9
save_png = True
outfile = "foto_agujero.png"

def acceleration(x, y, vx, vy, k=bend_strength):
    """Aceleración central estilo gravitacional: -k * r_hat / r^2 (vector form).
       Implementada como -k * r_vec / r^3 to get magnitude ~1/r^2.
       Es una aproximación visual; no es la expresión exacta de geodésicas."""
    r = np.hypot(x, y)
    if r == 0:
        return 0.0, 0.0
    ax = -k * x / (r**3)
    ay = -k * y / (r**3)
    return ax, ay

def rk4_step(x, y, vx, vy, dt):
    ax1, ay1 = acceleration(x, y, vx, vy)
    k1x, k1y = vx, vy
    k1vx, k1vy = ax1, ay1

    ax2, ay2 = acceleration(x + 0.5*dt*k1x, y + 0.5*dt*k1y,
                           vx + 0.5*dt*k1vx, vy + 0.5*dt*k1vy)
    k2x, k2y = vx + 0.5*dt*k1vx, vy + 0.5*dt*k1vy
    k2vx, k2vy = ax2, ay2

    ax3, ay3 = acceleration(x + 0.5*dt*k2x, y + 0.5*dt*k2y,
                           vx + 0.5*dt*k2vx, vy + 0.5*dt*k2vy)
    k3x, k3y = vx + 0.5*dt*k2vx, vy + 0.5*dt*k2vy
    k3vx, k3vy = ax3, ay3

    ax4, ay4 = acceleration(x + dt*k3x, y + dt*k3y,
                           vx + dt*k3vx, vy + dt*k3vy)
    k4x, k4y = vx + dt*k3vx, vy + dt*k3vy
    k4vx, k4vy = ax4, ay4

    x_new = x + dt*(k1x + 2*k2x + 2*k3x + k4x)/6
    y_new = y + dt*(k1y + 2*k2y + 2*k3y + k4y)/6
    vx_new = vx + dt*(k1vx + 2*k2vx + 2*k3vx + k4vx)/6
    vy_new = vy + dt*(k1vy + 2*k2vy + 2*k3vy + k4vy)/6

    return x_new, y_new, vx_new, vy_new

def init_rays_corner_top_left(n, corner_x=-view_radius, corner_y=+view_radius, spread_angle=0.7, speed=1.2):
    """Muchos rayos saliendo desde la esquina superior izquierda con pequeño spread angular."""
    px, py = corner_x, corner_y
    vec = np.array([-px, -py])
    base_angle = np.arctan2(vec[1], vec[0])
    angles = base_angle + np.linspace(-spread_angle, spread_angle, n)
    xs = np.full(n, px, dtype=float)
    ys = np.full(n, py, dtype=float)
    vxs = np.cos(angles) * speed
    vys = np.sin(angles) * speed
    norms = np.hypot(vxs, vys)
    vxs = vxs / norms * 0.9
    vys = vys / norms * 0.9
    return xs, ys, vxs, vys

def init_rays_parallel_left(n, x_start=-view_radius, y_min=-view_radius*0.9, y_max=view_radius*0.9, speed=1.0):
    """Rayo paralelos apuntando a la derecha (desde la izquierda), distribuido en y."""
    xs = np.full(n, x_start, dtype=float)
    ys = np.linspace(y_min, y_max, n, dtype=float)
    vxs = np.ones(n) * speed
    vys = np.zeros(n)
    return xs, ys, vxs, vys

if mode == "corner_top_left":
    x0, y0, vx0, vy0 = init_rays_corner_top_left(n_rays)
elif mode == "parallel_left":
    x0, y0, vx0, vy0 = init_rays_parallel_left(n_rays)
else:
    raise ValueError("mode desconocido")

start_time = time.time()

paths = [ [] for _ in range(n_rays) ]
alive = np.ones(n_rays, dtype=bool)

for i in trange(n_rays, desc="Integrando rayos"):
    x = float(x0[i]); y = float(y0[i]); vx = float(vx0[i]); vy = float(vy0[i])
    for step in range(steps_max):
        r = np.hypot(x, y)
        if r <= r_h:
            break
        if r > 1.5*view_radius:
            break
        paths[i].append((x, y))
        x, y, vx, vy = rk4_step(x, y, vx, vy, dt)

end_time = time.time()
print(f"Integración completada en {end_time - start_time:.1f} s. Rayos: {n_rays}, pasos max por rayo: {steps_max}")

fig, ax = plt.subplots(figsize=(8,8))
ax.set_facecolor('black')
ax.set_xlim(-view_radius, view_radius)
ax.set_ylim(-view_radius, view_radius)
ax.set_aspect('equal', adjustable='box')

horizon = plt.Circle((0,0), r_h, color='black', zorder=10)
ax.add_artist(horizon)
for k in range(1, 12):
    ax.add_artist(plt.Circle((0,0), r_h + 0.02*k, color='orange', alpha=0.03, zorder=9-k))

linewidth = 0.5
alpha = 0.03
color = (1.0, 0.9, 0.2)

min_ds = []
for path in paths:
    if len(path) == 0:
        min_ds.append(view_radius)
    else:
        arr = np.array(path)
        rs = np.hypot(arr[:,0], arr[:,1])
        min_ds.append(rs.min())

min_ds = np.array(min_ds)
norm = Normalize(vmin=min_ds.min(), vmax=min_ds.max())

for i, path in enumerate(paths):
    if len(path) < 2:
        continue
    arr = np.array(path)
    mod_alpha = alpha * (1.5 - 1.2*norm(min_ds[i]))
    ax.plot(arr[:,0], arr[:,1], color=color, linewidth=linewidth, alpha=max(0.005, mod_alpha), solid_capstyle='round')

ax.set_title("Foto estática: trayectorias de fotones alrededor del agujero negro", color='white')
ax.tick_params(colors='white')
ax.set_xticks([]); ax.set_yticks([])

plt.tight_layout()
if save_png:
    plt.savefig(outfile, dpi=300, bbox_inches='tight', facecolor='black')
    print(f"Guardado: {outfile}")

plt.show()

import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm
from matplotlib.colors import Normalize

G  = 1.0
c  = 1.0
M  = 1.0
r_h = 2 * G * M / c**2

view_radius = 10.0

n_rays = 250

x0 = np.ones(n_rays) * -10.0

y0 = np.linspace(-view_radius, view_radius, n_rays)

z0 = np.linspace(-3.0, 3.0, n_rays)

vx0 = np.ones(n_rays) * 1.0
vy0 = np.zeros(n_rays)
vz0 = np.zeros(n_rays)

def accel(x, y, z):
    """Aceleración gravitacional tipo Newtoniano en 3D."""
    r = np.sqrt(x*x + y*y + z*z)
    r = max(r, 1e-6)
    a = -G * M / r**3
    return a*x, a*y, a*z

def rk4(x, y, z, vx, vy, vz, dt):
    # k1
    ax1, ay1, az1 = accel(x, y, z)
    k1x, k1y, k1z = vx, vy, vz
    k1vx, k1vy, k1vz = ax1, ay1, az1

    # k2
    ax2, ay2, az2 = accel(x + 0.5*dt*k1x,
                           y + 0.5*dt*k1y,
                           z + 0.5*dt*k1z)
    k2x  = vx + 0.5*dt*k1vx
    k2y  = vy + 0.5*dt*k1vy
    k2z  = vz + 0.5*dt*k1vz
    k2vx, k2vy, k2vz = ax2, ay2, az2

    # k3
    ax3, ay3, az3 = accel(x + 0.5*dt*k2x,
                           y + 0.5*dt*k2y,
                           z + 0.5*dt*k2z)
    k3x  = vx + 0.5*dt*k2vx
    k3y  = vy + 0.5*dt*k2vy
    k3z  = vz + 0.5*dt*k2vz
    k3vx, k3vy, k3vz = ax3, ay3, az3

    # k4
    ax4, ay4, az4 = accel(x + dt*k3x,
                           y + dt*k3y,
                           z + dt*k3z)
    k4x  = vx + dt*k3vx
    k4y  = vy + dt*k3vy
    k4z  = vz + dt*k3vz
    k4vx, k4vy, k4vz = ax4, ay4, az4

    # Fusión
    xn  = x  + (dt/6)*(k1x + 2*k2x + 2*k3x + k4x)
    yn  = y  + (dt/6)*(k1y + 2*k2y + 2*k3y + k4y)
    zn  = z  + (dt/6)*(k1z + 2*k2z + 2*k3z + k4z)

    vxn = vx + (dt/6)*(k1vx + 2*k2vx + 2*k3vx + k4vx)
    vyn = vy + (dt/6)*(k1vy + 2*k2vy + 2*k3vy + k4vy)
    vzn = vz + (dt/6)*(k1vz + 2*k2vz + 2*k3vz + k4vz)

    return xn, yn, zn, vxn, vyn, vzn

dt = 0.01
steps_max = 15000

paths = []

print("\nIntegrando fotones 3D...")
for i in tqdm(range(n_rays)):
    x, y, z = x0[i], y0[i], z0[i]
    vx, vy, vz = vx0[i], vy0[i], vz0[i]

    px, py = [], []

    for _ in range(steps_max):

        r = np.sqrt(x*x + y*y + z*z)
        if r <= r_h:
            break

        px.append(x)
        py.append(y)

        # siguiente paso RK4
        x, y, z, vx, vy, vz = rk4(x, y, z, vx, vy, vz, dt)

        # salir del área visible
        if abs(x) > view_radius or abs(y) > view_radius:
            break

    paths.append((px, py))

fig, ax = plt.subplots(figsize=(6,6))

circle = plt.Circle((0,0), r_h, color='black')
ax.add_patch(circle)

for px, py in paths:
    if len(px) > 1:
        ax.plot(px, py, color=(1.0, 0.9, 0.1, 0.15))

ax.set_xlim(-view_radius, view_radius)
ax.set_ylim(-view_radius, view_radius)
ax.set_aspect('equal')
ax.set_facecolor('black')

plt.show()

import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm

G = 1.0
c = 1.0
M = 1.0
r_h = 2 * G * M / c**2
view_radius = 10.0

n_side = 150

n_rays = 4 * n_side

x0 = np.zeros(n_rays)
y0 = np.zeros(n_rays)
z0 = np.zeros(n_rays)

vx0 = np.zeros(n_rays)
vy0 = np.zeros(n_rays)
vz0 = np.zeros(n_rays)

idx = 0
ys = np.linspace(-view_radius, view_radius, n_side)
zs = np.linspace(-3, 3, n_side)

for i in range(n_side):
    x0[idx] = -view_radius
    y0[idx] = ys[i]
    z0[idx] = zs[i]
    vx0[idx] = +1.0
    vy0[idx] = 0.0
    vz0[idx] = 0.0
    idx += 1

for i in range(n_side):
    x0[idx] = +view_radius
    y0[idx] = ys[i]
    z0[idx] = zs[i]
    vx0[idx] = -1.0    # hacia -x
    vy0[idx] = 0.0
    vz0[idx] = 0.0
    idx += 1

xs = np.linspace(-view_radius, view_radius, n_side)

for i in range(n_side):
    x0[idx] = xs[i]
    y0[idx] = +view_radius
    z0[idx] = zs[i]
    vx0[idx] = 0.0
    vy0[idx] = -1.0   # salen hacia abajo
    vz0[idx] = 0.0
    idx += 1

for i in range(n_side):
    x0[idx] = xs[i]
    y0[idx] = -view_radius
    z0[idx] = zs[i]
    vx0[idx] = 0.0
    vy0[idx] = +1.0   # salen hacia arriba
    vz0[idx] = 0.0
    idx += 1


def accel(x, y, z):
    r = np.sqrt(x*x + y*y + z*z)
    r = max(r, 1e-6)
    a = -G * M / r**3
    return a*x, a*y, a*z

def rk4(x, y, z, vx, vy, vz, dt):

    # k1
    ax1, ay1, az1 = accel(x, y, z)
    k1x, k1y, k1z = vx, vy, vz
    k1vx, k1vy, k1vz = ax1, ay1, az1

    # k2
    ax2, ay2, az2 = accel(
        x + 0.5*dt*k1x,
        y + 0.5*dt*k1y,
        z + 0.5*dt*k1z
    )
    k2x = vx + 0.5*dt*k1vx
    k2y = vy + 0.5*dt*k1vy
    k2z = vz + 0.5*dt*k1vz
    k2vx, k2vy, k2vz = ax2, ay2, az2

    # k3
    ax3, ay3, az3 = accel(
        x + 0.5*dt*k2x,
        y + 0.5*dt*k2y,
        z + 0.5*dt*k2z
    )
    k3x = vx + 0.5*dt*k2vx
    k3y = vy + 0.5*dt*k2vy
    k3z = vz + 0.5*dt*k2vz
    k3vx, k3vy, k3vz = ax3, ay3, az3

    # k4
    ax4, ay4, az4 = accel(
        x + dt*k3x,
        y + dt*k3y,
        z + dt*k3z
    )
    k4x = vx + dt*k3vx
    k4y = vy + dt*k3vy
    k4z = vz + dt*k3vz
    k4vx, k4vy, k4vz = ax4, ay4, az4

    # COMBINACIÓN
    xn = x + (dt/6)*(k1x + 2*k2x + 2*k3x + k4x)
    yn = y + (dt/6)*(k1y + 2*k2y + 2*k3y + k4y)
    zn = z + (dt/6)*(k1z + 2*k2z + 2*k3z + k4z)

    vxn = vx + (dt/6)*(k1vx + 2*k2vx + 2*k3vx + k4vx)
    vyn = vy + (dt/6)*(k1vy + 2*k2vy + 2*k3vy + k4vy)
    vzn = vz + (dt/6)*(k1vz + 2*k2vz + 2*k3vz + k4vz)

    return xn, yn, zn, vxn, vyn, vzn


dt = 0.01
steps_max = 15000

paths = []

print("\nIntegrando fotones 3D desde TODAS las paredes...")
for i in tqdm(range(n_rays)):

    x, y, z = x0[i], y0[i], z0[i]
    vx, vy, vz = vx0[i], vy0[i], vz0[i]

    px, py = [], []

    for _ in range(steps_max):

        r = np.sqrt(x*x + y*y + z*z)
        if r <= r_h:
            break

        px.append(x)
        py.append(y)

        x, y, z, vx, vy, vz = rk4(x, y, z, vx, vy, vz, dt)

        if abs(x) > view_radius or abs(y) > view_radius:
            break

    paths.append((px, py))


fig, ax = plt.subplots(figsize=(6,6))

circle = plt.Circle((0,0), r_h, color='black')
ax.add_patch(circle)

for px, py in paths:
    if len(px) > 1:
        ax.plot(px, py, color=(1.0, 0.9, 0.1, 0.1))

ax.set_xlim(-view_radius, view_radius)
ax.set_ylim(-view_radius, view_radius)
ax.set_aspect('equal')
ax.set_facecolor('black')

plt.show()

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

G = 1.0
c = 1.0
M = 1.0
r_h = 2 * M

def accel(x, y, z):
    r = np.sqrt(x*x + y*y + z*z)
    if r < 1e-6:
        r = 1e-6
    a = -G * M / r**3
    return a*x, a*y, a*z

def rk4_step(x, y, z, vx, vy, vz, dt):

    # k1
    ax1, ay1, az1 = accel(x, y, z)
    k1x,  k1y,  k1z  = vx, vy, vz
    k1vx, k1vy, k1vz = ax1, ay1, az1

    # k2
    ax2, ay2, az2 = accel(
        x + 0.5*dt*k1x,
        y + 0.5*dt*k1y,
        z + 0.5*dt*k1z
    )
    k2x  = vx + 0.5*dt*k1vx
    k2y  = vy + 0.5*dt*k1vy
    k2z  = vz + 0.5*dt*k1vz
    k2vx, k2vy, k2vz = ax2, ay2, az2

    # k3
    ax3, ay3, az3 = accel(
        x + 0.5*dt*k2x,
        y + 0.5*dt*k2y,
        z + 0.5*dt*k2z
    )
    k3x  = vx + 0.5*dt*k2vx
    k3y  = vy + 0.5*dt*k2vy
    k3z  = vz + 0.5*dt*k2vz
    k3vx, k3vy, k3vz = ax3, ay3, az3

    # k4
    ax4, ay4, az4 = accel(
        x + dt*k3x,
        y + dt*k3y,
        z + dt*k3z
    )
    k4x  = vx + dt*k3vx
    k4y  = vy + dt*k3vy
    k4z  = vz + dt*k3vz
    k4vx, k4vy, k4vz = ax4, ay4, az4

    # Combinar
    xn = x + (dt/6)*(k1x + 2*k2x + 2*k3x + k4x)
    yn = y + (dt/6)*(k1y + 2*k2y + 2*k3y + k4y)
    zn = z + (dt/6)*(k1z + 2*k2z + 2*k3z + k4z)

    vxn = vx + (dt/6)*(k1vx + 2*k2vx + 2*k3vx + k4vx)
    vyn = vy + (dt/6)*(k1vy + 2*k2vy + 2*k3vy + k4vy)
    vzn = vz + (dt/6)*(k1vz + 2*k2vz + 2*k3vz + k4vz)

    return xn, yn, zn, vxn, vyn, vzn


x0 = -10.0
y0 = 2.0
z0 = 1.5

vx0 = 1.0
vy0 = 0.1
vz0 = -0.05

dt = 0.01
steps = 20000

tray_x = []
tray_y = []
tray_z = []

x, y, z = x0, y0, z0
vx, vy, vz = vx0, vy0, vz0

for i in range(steps):

    r = np.sqrt(x*x + y*y + z*z)
    if r <= r_h:
        print("El fotón cayó al horizonte en el paso:", i)
        break

    tray_x.append(x)
    tray_y.append(y)
    tray_z.append(z)

    x, y, z, vx, vy, vz = rk4_step(x, y, z, vx, vy, vz, dt)

    if abs(x) > 20 or abs(y) > 20 or abs(z) > 20:
        print("El fotón salió del dominio.")
        break


print("Puntos totales integrados:", len(tray_x))

fig = plt.figure(figsize=(7,7))
ax = fig.add_subplot(111, projection='3d')

# Trayectoria
ax.plot(tray_x, tray_y, tray_z, color='gold', linewidth=1)

# Horizonte de sucesos (esfera)
u = np.linspace(0, 2*np.pi, 30)
v = np.linspace(0, np.pi, 30)
xs = r_h * np.outer(np.cos(u), np.sin(v))
ys = r_h * np.outer(np.sin(u), np.sin(v))
zs = r_h * np.outer(np.ones_like(u), np.cos(v))
ax.plot_surface(xs, ys, zs, color='black', alpha=0.8)

ax.set_xlim(-10, 10)
ax.set_ylim(-10, 10)
ax.set_zlim(-10, 10)

ax.set_xlabel("x")
ax.set_ylabel("y")
ax.set_zlabel("z")
ax.set_title("en 3d")

plt.show()

